name: 'Ghost API Action'
description: 'Send a call to the Ghost API'
inputs:
    url:
        description: 'Ghost URL'
        required: true
    key:
        description: 'Your Ghost Admin API Key'
        required: true
    version:
        description: 'API Version'
        required: false
        default: 'v3'
    page:
        description: 'ID of page to update'
        required: true
    readme:
        description: 'Path to README.md'
        required: false
        default: 'README.md'
outputs:
    response:
        description: 'Ghost API Response'
runs:
    using: 'node12'
    main: 'dist/index.js'
