name: 'Ghost API Action'
description: 'Send a call to the Ghost API'
inputs:
    ghost-url:
        description: 'Ghost URL'
        required: true
    method:
        description: 'Method'
        required: false
        default: 'GET'
    data:
        description: 'Data to Send'
        required: false
        default: '{}'
    key:
        description: 'Your Ghost Admin API Key'
        required: true
    timeout:
        description: 'Request Timeout in Sec'
        required: false
        default: '300'
outputs:
    response:
        description: 'Ghost API Response'
runs:
    using: 'node12'
    main: 'dist/index.js'
